docs: Feature design template update
Flank/flank-dashboard pull request #1441
Opened 2021-05-31 17:08 UTC by solid-vladlaba

Explain the Analysis section with subsections to simplify feature analysis in the future.

## Checklist

- [x] Documented

2021-05-31 17:15 UTC, solid-vladlaba commented
I have read the CLA Document and I hereby sign the CLA

2021-05-31 17:15 UTC, solid-vladlaba commented
recheck

2021-06-01 12:56 UTC, illia-romanenko requested changes
Great job capturing it all! I've made a couple of suggestions but overall it could benefit significantly in other team members understanding this template, thanks @solid-vladlaba !

2021-06-01 12:56 UTC, illia-romanenko commented on docs/19_feature_design_template.md
> +- In what way the new feature integrates into the project's functionality?
```suggestion
- Is the new feature a part of the existing component? Does it complement or improve/upgrade this component?
- Is the new feature should be a part of a standalone component? How this component is going to interact with other components?
```

will this be sufficient?

2021-06-01 17:25 UTC, illia-romanenko requested changes
Looks great, thanks @solid-vladlaba ! Please see if couple additional items make sense and that should be it. Thanks for leading this effort.

2021-06-01 17:25 UTC, illia-romanenko commented on docs/19_feature_design_template.md
> +Once the requirements are defined, one should consider the feature and conclude if this feature makes sense for the project. In the context of usability and project's purposes, one should answer the
```suggestion
One should answer the following: 
```

2021-06-01 17:25 UTC, illia-romanenko commented on docs/19_feature_design_template.md
> +Once the feature makes sense, one should review is it feasible. More precisely, one should conclude is it possible to implement the feature taking into account the listed requirements from the [Requi
```suggestion
```

Let's skip references to the future sections, I think for now we can limit to the above questions.

2021-06-01 17:36 UTC, illia-romanenko approved these changes
LGTM - thanks @solid-vladlaba !

2021-06-01 17:37 UTC, merged