docs: Metrics storybook analysis document
Flank/flank-dashboard pull request #1444
Opened 2021-06-03 08:20 UTC by solid-tetianamovlian

Fixes #1435 

## Checklist

- [ ] Documented

2021-06-03 16:00 UTC, solid-vladlaba requested changes
Well done, @solid-tetianamovlian @solid-maxim! I've added a couple of suggestions below - please let me know what you think!

2021-06-03 16:00 UTC, solid-vladlaba commented on metrics/web/docs/features/storybook/01_create_metrics_storybook.md
> +
It seems like the following sections are missing: 
    - [Prototyping](https://github.com/Flank/flank-dashboard/blob/master/docs/19_feature_design_template.md#prototyping)
    - [System modeling](https://github.com/Flank/flank-dashboard/blob/master/docs/19_feature_design_template.md#system-modeling)

2021-06-09 14:35 UTC, solid-vovabeloded requested changes
Great job, @solid-maxim & @solid-tetianamovlian! I've added a couple of suggestions here - please take a look.

2021-06-09 14:35 UTC, solid-vovabeloded commented on metrics/web/docs/features/storybook/01_metrics_storybook_design.md
> +- Contains a list of inputs to change widgets' appearance (height, width, color, etc.).
:readable: 
```suggestion
- Provides an ability to change the widgets' appearance (height, width, color, etc.).
```
What do you think?

2021-06-09 14:35 UTC, solid-vovabeloded commented on metrics/web/docs/features/storybook/01_metrics_storybook_design.md
> +1. [Storyboard](https://pub.dev/packages/storyboard)
:readable: Would it be great to convert this numbered list into separate sub-sections?

2021-06-09 14:35 UTC, solid-vovabeloded commented on metrics/web/docs/features/storybook/01_metrics_storybook_design.md
> +- Takes extra time to implement a new UI element.
🏷️ 
```suggestion
- Takes extra time to implement new UI elements.
```
?

2021-06-09 14:35 UTC, solid-vovabeloded commented on metrics/web/docs/features/storybook/01_metrics_storybook_design.md
> +### Prototyping
🔨 I think the prototyping section should contain information that confirms that the feature implementation is possible. For example, we can prove that we can extract the part of the Metrics Web application into a separate package by providing appropriate code snippets. What do you think?

2021-06-10 09:08 UTC, solid-vovabeloded requested changes
Well done, @solid-maxim & @solid-tetianamovlian! I've added a few more minor suggestions here - please take a look.

2021-06-10 09:08 UTC, solid-vovabeloded commented on metrics/web/docs/features/storybook/01_metrics_storybook_design.md
> +Before defining requirements to the feature, we should determine which components from the Metrics Web Application should be included in the storybook.
:tw:
```suggestion
Before defining requirements to the feature, we should determine which components from the Metrics Web Application the storybook should include.
```
Please, prefer active voice to passive voice. See [Google Technical Writing](https://developers.google.com/tech-writing/one/active-voice#prefer_active_voice_to_passive_voice) for more details.

2021-06-10 09:08 UTC, solid-vovabeloded commented on metrics/web/docs/features/storybook/01_metrics_storybook_design.md
> +According to the [widget structure organization document](https://github.com/Flank/flank-dashboard/blob/master/metrics/web/docs/03_widget_structure_organization.md#applying-a-theme-to-a-widget-appear
🏷️
```suggestion
According to the [widget structure organization document](https://github.com/Flank/flank-dashboard/blob/master/metrics/web/docs/03_widget_structure_organization.md#applying-a-theme-to-a-widget-appearance), common widgets use the Metrics theme. Thus to display these widgets in the storybook correctly, we should move the Metrics theme along with them. The disadvantage of moving common widgets is the loss of the ability to customize them as base widgets.
```

2021-06-10 09:08 UTC, solid-vovabeloded commented on metrics/web/docs/features/storybook/01_metrics_storybook_design.md
> +There are simple classes, which provide all the logic to start writing the storybook. It is just a little package, that helps to reduce a boilerplate.
🏷️ 
```suggestion
There are simple classes, which provide all the logic to start writing the storybook. It is just a little package that helps to reduce a boilerplate.
```

2021-06-10 14:59 UTC, solid-vovabeloded approved these changes
LGTM, thanks @solid-maxim & @solid-tetianamovlian!

2021-06-10 15:43 UTC, solid-vladlaba approved these changes
LGTM, thanks @solid-maxim & @solid-tetianamovlian!

2021-06-10 15:43 UTC, merged