feat: Update the `RouteConfiguration` class to include the `parameters` field
Flank/flank-dashboard pull request #1451
Opened 2021-06-10 14:09 UTC by solid-daniyilyevtyushkin

Fixes #1450

## Checklist

- [x] Documented
- [x] Unit tested

2021-06-11 11:19 UTC, solid-vovabeloded requested changes
Great job, @solid-daniyilyevtyushkin & @solid-yevheniiashchypeleva! I've added a couple of suggestions here - please take a look. Overall, the code looks clean and well-structured - thanks!

2021-06-11 11:19 UTC, solid-vovabeloded commented on metrics/web/lib/common/presentation/navigation/route_configuration/route_configuration_location_converter.dart
> +/// to a location [String].
🏷️
```suggestion
/// A class that provides a method for converting the [RouteConfiguration]
/// to a location [String].
```
What do you think?

2021-06-11 11:19 UTC, solid-vovabeloded commented on metrics/web/test/common/presentation/navigation/metrics_route_information_parser_test.dart
> +      ".restoreRouteInformation() delegates converting the route configuration to a location to the route configuration location converter if it is not null",
🏷️
```suggestion
      ".restoreRouteInformation() delegates converting the route configuration to the route configuration location converter if the configuration is not null",
```
Would it be a bit more clear?

2021-06-14 14:12 UTC, solid-vladlaba requested changes
Well done, @solid-daniyilyevtyushkin @solid-yevheniiashchypeleva! I've added a few suggestions below - please let me know what you think!

2021-06-14 15:03 UTC, solid-vladlaba approved these changes
LGTM, thanks @solid-daniyilyevtyushkin @solid-yevheniiashchypeleva!:rocket:

2021-06-14 15:04 UTC, solid-vovabeloded approved these changes
LGTM, thanks @solid-daniyilyevtyushkin & @solid-yevheniiashchypeleva!

2021-06-14 15:05 UTC, merged