docs: Design update/redeploy feature
Flank/flank-dashboard pull request #1459
Opened 2021-06-16 12:34 UTC by solid-yuriiuvarov

Fixes #1439 

## Checklist

- [x] Documented

2021-06-17 12:17 UTC, solid-vladlaba requested changes
Well done, @solid-dimakoniaiev @solid-yuriiuvarov! I've added a couple of suggestions below - please let me know what you think!

2021-06-17 12:17 UTC, solid-vladlaba commented on metrics/cli/docs/features/update/06_update_feature.md
> +The `Updater` class is needed to separate the redeployment logic from the [`UpdateCommand`](#updatecommand). It has the `update` method that encapsulates the interaction with the external [`Services`
🏷️ 
```suggestion
The `Updater` class encapsulates the redeployment logic. The `UpdateCommand` uses the `Updater` with the parsed configurations. The `Updater` has the `update` method that interacts with the external [`Services`](https://github.com/Flank/flank-dashboard/blob/master/metrics/cli/docs/01_metrics_cli_design.md#service) and redeploys the latest version of the Metrics Web Application to the Firebase using the `UpdateConfig`.

To create an `Updater`, the `UpdateCommand` uses the `UpdaterFactory`. This factory provides the `Updater` instance with all the required services and returns the ready-to-use instance to the `Updater`.
```

2021-06-17 12:17 UTC, solid-vladlaba commented on metrics/cli/docs/features/diagrams/update_command_integration_class_diagram.puml
> +    class CommandRunner{}
🏷️ 
```suggestion
    class CommandRunner {}
```

2021-06-17 12:17 UTC, solid-vladlaba commented on metrics/cli/docs/features/diagrams/update_command_integration_class_diagram.puml
> +        + run() : Future<void>
🏷️ 
Please apply where necessary.
```suggestion
        + name: String
        + description: String
        + run(): Future<void>
```

2021-06-17 12:17 UTC, solid-vladlaba commented on metrics/cli/docs/features/diagrams/yaml_config_parser_class_diagram.puml
> +        package config {
:readable: 
```suggestion
package cli.updater.config {
```

2021-06-17 12:17 UTC, solid-vladlaba commented on metrics/cli/docs/features/diagrams/updater_class_diagram.puml
> +    package file {
:readable:
```suggestion
package util.file {
```

2021-06-17 12:17 UTC, solid-vladlaba commented on metrics/cli/docs/features/diagrams/yaml_config_parser_class_diagram.puml
> +SentryConfig -up-o UpdateConfig
🏗️ 
Should it be a composition instead of aggregation? Also, how about adding some numbers to indicate instance relation (one-to-one, one-to-many)?

2021-06-17 12:17 UTC, solid-vladlaba commented on metrics/cli/docs/features/diagrams/update_command_sequence_diagram.puml
> +
:readable:
The diagram contains a lot of callings to different services that are not described in the document. Should we provide more details before introducing this diagram?

2021-06-23 10:50 UTC, illia-romanenko requested changes
Great job @solid-dimakoniaiev and @solid-yuriiuvarov! I've added couple of minor things but overall it looks very good. Thanks!

2021-06-23 10:50 UTC, illia-romanenko commented on metrics/cli/docs/features/update/06_update_feature.md
> +![Update config diagram](http://www.plantuml.com/plantuml/proxy?cache=no&fmt=svg&src=https://github.com/Flank/flank-dashboard/raw/update_feature_design/metrics/cli/docs/features/update/diagrams/updat
Should we use here a simple snippet from configuration_template (without detailed documentation) as this diagram could look a bit confusing due to 2 rows layout where a reader could think that the second column somehow explains what value from the first column means? :readable:

2021-06-23 10:50 UTC, illia-romanenko commented on metrics/cli/docs/features/update/06_update_feature.md
> +7. Cleanup the created directories, etc.
It looks like that it performs less steps actually as it uses `Updater` to actually update redeploy. Should we leave here something simpler - like: "Uses Updater to ...." and then in `Updater` section specify what redeployment logic from this list is actually performed in Updater. :readable:

2021-06-23 10:50 UTC, illia-romanenko commented on metrics/cli/docs/features/update/config/configuration_template.yaml
> +# - https://docs.sentry.io/product/
Should we move the Sentry link closer to the Sentry section? :readable:

2021-06-23 10:50 UTC, illia-romanenko commented on metrics/cli/docs/features/update/config/configuration_template.yaml
> +# The `firebase` key defines that the following source config stands for the Metrics components in the Firebase.
```suggestion
# The `firebase` key defines Firebase deployment configuration.
```
:readable:

2021-06-23 10:50 UTC, illia-romanenko commented on metrics/cli/docs/features/update/config/configuration_template.yaml
> +  # The defined pipeline must belong to the organization with the defined slug.
I'm not sure that `slug` is relevant to the google_sign_in_client id 

🏷️

2021-06-23 10:50 UTC, illia-romanenko commented on metrics/cli/docs/features/update/config/configuration_template.yaml
> +# The `sentry` key defines that the following source config stands for the Sentry configuration.
Should we add that this section is optional?
:readability:

2021-06-23 10:50 UTC, illia-romanenko commented on metrics/cli/docs/features/update/config/configuration_template.yaml
> +  # A Sentry Access Token that is used to authenticate CLI requests.
```suggestion
  # A Sentry Authentication Token that is used to authenticate CLI requests.
```
🏷️

2021-06-23 10:50 UTC, illia-romanenko commented on metrics/cli/docs/features/update/config/configuration_template.yaml
> +  # You can find an access token on the Auth Tokens page in Account Settings on Sentry.
```suggestion
  # You can find an auth token on the Auth Tokens page in Account Settings on Sentry.
```

🏷️

2021-06-23 13:44 UTC, illia-romanenko approved these changes
LGTM - thanks @solid-yuriiuvarov @solid-dimakoniaiev !

2021-06-23 13:52 UTC, merged