docs: Metrics storybook design
Flank/flank-dashboard pull request #1462
Opened 2021-06-17 13:22 UTC by solid-tetianamovlian

Fixes #1454 

## Checklist

- [ ] Documented

2021-06-24 18:01 UTC, solid-dimakoniaiev requested changes
Well done, @solid-maxim @solid-tetianamovlian! I've added a couple of suggestions below - please let me know what you think!

2021-06-24 18:04 UTC, solid-dimakoniaiev commented on metrics/web/docs/features/storybook/diagrams/metrics_storybook_class_diagram.puml
> +        + selectedTheme : ThemeType
Please apply where necessary.

```suggestion
        - _selectedTheme: ThemeType
        + isDark: bool
        + selectedTheme: ThemeType
```

2021-07-01 12:05 UTC, solid-vovabeloded requested changes
Well done, @solid-tetianamovlian & @solid-maxim! I've added few suggestions here - please take a look.

2021-07-07 14:01 UTC, solid-maxim commented
Close this PR for now as we want to improve the storybook design document.

2021-07-07 14:01 UTC, closed without merging