feat: Public dashboard security rules
Flank/flank-dashboard pull request #1558
Opened 2021-08-10 16:48 UTC by solid-maxim

Fixes #1557 

## Checklist

- [ ] Documented
- [ ] Unit tested

2021-08-12 07:06 UTC, illia-romanenko requested changes
Looks good. Thanks, @solid-maxim. Added a couple of comments - let me know what you think. Glad that the structure that we have allows adding such checks so easily.

2021-08-12 07:06 UTC, illia-romanenko commented on metrics/firebase/firestore/rules/firestore.rules
> +  function isSignInProviderAnonymous() {
Should we check that the public dashboard is enabled too?

2021-08-12 07:06 UTC, illia-romanenko commented on metrics/firebase/firestore/rules/firestore.rules
> +      allow read: if isAccessAuthorized(database) || isSignInProviderAnonymous();
Should we improve naming a bit to make sure that it's readable & understandable how those 2 checks are different and what are the use cases?

2021-08-16 09:21 UTC, solid-anatolyeva commented
I have read the CLA Document and I hereby sign the CLA

2021-08-20 09:12 UTC, closed without merging